@base=http://localhost:8080

### Create a new todo

POST {{base}}/todos
Content-Type: application/json

{
  "id": 1,
  "name":"Pick up groceries",
  "completed":false
}

### Get todos
GET {{base}}/todos

### Get specific todo

GET {{base}}/todos/1

### Update todo

PUT {{base}}/todos/1
Content-Type: application/json

{
  "id": 1,
  "name":"walk dog",
  "completed": true
}

### Toggle todo

POST {{base}}/toggle/1
